
services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: simplebank_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank

  mailpit:
    image: axllent/mailpit:latest
    container_name: simplebank_mailpit
    ports:
      - "8025:8025" 
  api:
    container_name: simplebank_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

  
